name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 클론
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 빌드
      - name: Build project
        env:
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
        run: npm run build

      # 5. 배포 (GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 여기를 GITHUB_TOKEN으로 수정
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          user_name: GitHub Actions
          user_email: actions@github.com
